[package]
name = "rust-bar"
description = "A wayland status bar written and configured in rust"
authors = [ "Square-face <linus.michelsson@gmail.com>" ]
readme = "README.md"
repository = "https://github.com/Square-face/rust-bar.git"
keywords = [ "hyprland", "wayland", "status-bar", "gtk-layer-shell", "linux" ]
categories = [ "rendering", "gui" ]
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.26.0", features = [ "full" ] }
tracing-subscriber = "0.3.16"
gtk-layer-shell = "0.6.0"
lazy_static = "1.4.0"
hyprland = "0.3.1"
lxinfo = "0.1.2"
stray = "0.1.3"
glib = "0.17.2"
json = "0.12.4"
gtk = "0.17.0"

[profile.release]
codegen-units = 1
panic = "abort"
opt-level = "z"
strip = true
lto = "fat"
